<div class="zoniz-stream" account-name="<?=$this->getData('account_name')?>" stream-name="<?=$this->getData('stream_name')?>"></div>
<script>(function(d, s, id) { var js, fjs = d.getElementsByTagName(s)[0]; if (d.getElementById(id)) return; js = d.createElement(s); js.id = id; js.src = "https://s3-eu-west-1.amazonaws.com/eu.zoniz.com/zoniz/public/js/common/zoniz.stream.min.js?1370861275123"; fjs.parentNode.insertBefore(js, fjs); } (document, 'script', 'zoniz-stream'));</script>

